# Enable hint by default
EnableHintByDefault=False
# Enable emoji in hint
EnableEmoji=True
# Enable emoji in quickphrase
EnableQuickPhraseEmoji=True
# Candidates Per Page
PageSize=5

[Hint Trigger]
0=Control+Alt+H

[One Time Hint Trigger]
0=Control+Alt+J
