git:
  # https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_DiffRenderers.md
  # cycle between renderers with `|`
  diffRenderers:
    - type: extDiff
      command: difft --color=always --context={{diffContext}}
    - type: rawGit
      name: default
