import = ["~/.config/alacritty/rose-pine.toml"]
[window]
dimensions = { columns = 80, lines = 60 }
decorations = "Full"
opacity = 0.97
blur = true
startup_mode="Maximized"
title = "Terminal"
[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 18
[selection]
save_to_clipboard=true
[keyboard]
bindings = [
    { mods = "Super", key = "ArrowUp", action = "ToggleFullscreen"},
    { mods = "Super", key = "K", action = "ToggleFullscreen"}
]
