import = [
    "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
]
[window]
dimensions = { columns = 80, lines = 60 }
decorations = "Full"
opacity = 0.85
blur = true
startup_mode="Fullscreen"
title = "Terminal"
[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
size = 15
[selection]
save_to_clipboard=true
[keyboard]
bindings = [
    { mods = "Super", key = "ArrowUp", action = "ToggleFullscreen"},
    { mods = "Super", key = "K", action = "ToggleFullscreen"}
]
