import = [ "~/.config/alacritty/rose-pine.toml" ]

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
dimensions = { columns = 80, lines = 60 }
decorations = "Full"
opacity = 0.95
blur = true
startup_mode="Maximized"
title = "Terminal"

[font]
normal = { family = "MapleMono NF CN", style = "Regular" }
size = 18
offset = { x = 0, y = 0 }

[selection]
save_to_clipboard=true

[keyboard]
bindings = [
    { mods = "Super", key = "ArrowUp", action = "ToggleFullscreen"},
    { mods = "Super", key = "K", action = "ToggleFullscreen"}
]
